/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "map.h"

bool_t
xdr_MapFlag(register XDR *xdrs, MapFlag *objp)
{

	register long *buf;

	if (!xdr_enum(xdrs, (enum_t *)objp))
		return (FALSE);
	return (TRUE);
}

bool_t
xdr_Polyline(register XDR *xdrs, Polyline *objp)
{

	register long *buf;

	if (!xdr_int(xdrs, &objp->npoints))
		return (FALSE);
	if (!xdr_float(xdrs, &objp->lat1))
		return (FALSE);
	if (!xdr_float(xdrs, &objp->lat0))
		return (FALSE);
	if (!xdr_float(xdrs, &objp->lon1))
		return (FALSE);
	if (!xdr_float(xdrs, &objp->lon0))
		return (FALSE);
	if (!xdr_int(xdrs, &objp->flags))
		return (FALSE);
	return (TRUE);
}

bool_t
xdr_Point(register XDR *xdrs, Point *objp)
{

	register long *buf;

	if (!xdr_float(xdrs, &objp->lat))
		return (FALSE);
	if (!xdr_float(xdrs, &objp->lon))
		return (FALSE);
	return (TRUE);
}

bool_t
xdr_AltPoint(register XDR *xdrs, AltPoint *objp)
{

	register long *buf;

	if (!xdr_float(xdrs, &objp->lat))
		return (FALSE);
	if (!xdr_float(xdrs, &objp->lon))
		return (FALSE);
	if (!xdr_float(xdrs, &objp->alt))
		return (FALSE);
	return (TRUE);
}
