# $Id: Makefile.ini,v 1.5 1993-08-04 17:14:48 granger Exp $
#
# Bootstrap Makefile for Zeb distribution
#

       SHELL = /bin/sh
          RM = rm -f
          MV = mv
        MAKE = make
         TOP = .
 CURRENT_DIR = .
   CONFIGSRC = $(TOP)/config
    IMAKESRC = $(TOP)/imake
    IRULESRC = $(CONFIGSRC)
       IMAKE = $(IMAKESRC)/imake
  IMAKE_INCS = -I$(NEWTOP)$(CONFIGSRC) -I$(NEWTOP)$(IMAKESRC)
   IMAKE_CMD = $(NEWTOP)$(IMAKE) $(IMAKE_INCS) $(IMAKE_DEFINES)
       FLAGS = $(MFLAGS) -f Makefile.ini INCLUDES="-I../config" \
	       BOOTSTRAPCFLAGS="$(BOOTSTRAPCFLAGS)"

all:
	@echo "Please read the README file for installation instructions."
	@echo "You should be using make World to begin the installation."
	@echo "Do not name your log file make.log or it will be deleted."
	@echo "Check the configuration parameters in the config directory."
	@echo " "
	@echo "If the top-level Makefile gets corrupted, copy Makefile.ini
	@echo "to Makefile and try again."

World:
	@echo ""
	@echo "Building the Zeb distribution"
	@echo ""
	@echo "####################################################"
	@echo "#   Have you read the installation instructions?   #"
	@echo "####################################################"
	@echo ""
	@date
	@echo ""
	cd $(IMAKESRC); \
		$(MAKE) $(MFLAGS) -f Makefile.ini clean; \
		$(MAKE) $(MFLAGS) -f Makefile.ini \
			CC="$(CC)" \
			BOOTSTRAPCFLAGS="$(BOOTSTRAPCFLAGS)" \
			INCLUDES=-I../config
	-$(RM) Makefile.bak; $(MV) Makefile Makefile.bak
	$(IMAKE_CMD) -DTOPDIR=$(TOP) -DCURDIR=$(CURRENT_DIR)
	$(MAKE) $(MFLAGS) Makefiles
	$(MAKE) $(MFLAGS) clean
	$(MAKE) $(MFLAGS) includes
	$(MAKE) $(MFLAGS) depend
	$(MAKE) $(MFLAGS) $(WORLDOPTS) install
	@echo ""
	@date
	@echo ""
	@echo "Full build of Zeb complete"
	@echo ""

Makefile:
	cd $(IMAKESRC); \
		$(MAKE) $(MFLAGS) -f Makefile.ini clean; \
		$(MAKE) $(MFLAGS) -f Makefile.ini \
			CC="$(CC)" \
			BOOTSTRAPCFLAGS="$(BOOTSTRAPCFLAGS)" \
			INCLUDES=-I../config
	-$(RM) Makefile.bak; $(MV) Makefile Makefile.bak
	$(IMAKE_CMD) -DTOPDIR=$(TOP) -DCURDIR=$(CURRENT_DIR)
