#!/bin/sh

# T-REX kludge for field catalog conventions: Translate certain iss
# configurations and plot window names into their field catalog 
# designations.
#
# This maps the display config name and window name (eg iss1/class,
# iss-mapr/surfmet) to a platform and product, like (ISS1_Sounding, SkewT)
# and (ISS_MAPR_Surface, Surface_Met), then generates the field catalog
# file name from that using the base time.  Field catalog filenames:
#
#   research.<platform>.YYYYMMDDHHmm.<product>.png
#

catalog_translate() # config-name window-name platform-var product-var 
{
    config="$1"
    window="$2"

    # Defaults
    ptype="upperair"
    suffix=""
    product="$window"

    platform=`echo $config | tr a-z- A-Z_`
    # Override the platform as necessary
    case "$config" in
	iss1) platform="FP3" ;;
	iss2) platform="FP4" ;;
	iss3) platform="FP5" ;;
	iss4) platform="MP4" ;;
    esac

    # The window determines the platform suffix and product
    case "$window" in

	surf2*rad) suffix="Surface2"; product="radiation";;
	surf2*met) suffix="Surface2"; product="pth";;
	surf2*wind) suffix="Surface2"; product="wind";;
	surf*rad) suffix="Surface"; product="radiation";;
	surf*met) suffix="Surface"; product="pth";;
	surf*wind) suffix="Surface"; product="wind";;
	surfdiag) suffix="Surface"; product="diagnostics";;
	prof915l) suffix="Profiler"; product="wind_profile_low";;
	prof915h) suffix="Profiler"; product="wind_profile_high";;
	prof449-30m) suffix="Profiler"; product="wind_30m";;
	prof449-5m) suffix="Profiler"; product="wind_5m";;
	class) suffix="Sonde"; product="skewT";;
	rass) suffix="Profiler"; product="rass";;
	snow) suffix="Surface"; product="snow";;
	soap_24hr|soapmoments*)
	    suffix="Profiler"; product="moments";;
	con_snrw|nimawinds*) 
	    suffix="Profiler"; product="snr_winds";;
	con_moms|nimamoments*)
	    suffix="Profiler"; product="nima_consensus_moments";;
	con_rass|nimarass*)
	    suffix="Profiler"; product="nima_consensus_rass";;
	prof_200|soapprofiles*) 
	    suffix="Profiler"; product="profiles";;
	webcam)
	    suffix="Webcam"; product="photo";;
	skycamraw)
	    suffix="AllSkyCamera"; product="photo";;
	skycampano)
	    suffix="AllSkyCamera"; product="pano";;

    esac
    case "$window" in 
	surf*|snow*) ptype="surface" ;;
    esac

    platform="${ptype}.${platform}_${suffix}"
    if [ -z "$suffix" ]; then
	platform="${ptype}.${platform}"
    fi
    eval $3="$platform"
    eval $4="$product"
}



catalog_name() # config-name time-base window-name
{
    config="$1"
    base="$2"
    window="$3"

    catalog_translate "$config" "$window" platform product
    echo "${platform}"."${base}"."${product}"
}


