#! /usr/bin/env perl
#
# Given a list of png files on the command line, "sign" each one with
# a data disclaimer in the lower right corner.
#
# $Id: disclaim,v 1.4 2002-05-25 00:19:13 burghart Exp $

use lib "/usr/local/lib/GD-1.22/lib";
use GD;

foreach $png (@ARGV)
{
    
    print "disclaimer: $png\n";
    open (PNG,"< $png") || die "could not open $png";
    $im = newFromPng GD::Image(PNG) || die "creating GD image from $png";
    close PNG;

    ($width, $height) = $im->getBounds();

    # Allocate colors in the image
    ($white,$black,$red,$blue,$yellow) = 
	(
	 $im->colorAllocate(255, 255, 255),
	 $im->colorAllocate(0, 0, 0),
	 $im->colorAllocate(255, 0, 0),
	 $im->colorAllocate(0,0,255),
	 $im->colorAllocate(255,250,205)
	 );

    $im->interlaced(1);		# cool venetian blinds effect

    $x = $width / 3;
    $y = $height - 20;
    $msg = "Realtime data, not checked for quality";
    $font = gdMediumBoldFont;
    $im->string($font,$x,$y,"$msg",$red);

    open (PNG,"> $png") || die "could not open $png";
    print PNG $im->png();
    close PNG;

}
