#! /usr/bin/env perl
#
# $Id: issclass,v 1.3 2002-05-25 00:19:13 burghart Exp $
#
# Convert recent iss class files to ascii and ftp
#

# Top zebra directory
$ztop="/net/sssf3/lake_ice/zebra";
$zbin="$ztop/bin";
$ENV{'PATH'} = "$zbin:" . $ENV{'PATH'};

# Project directory
$project=".";

$joss = "/net/sssf3/lake_ice/joss";

if (system("ZEB_EVENTLOGGER=\"true\" $zbin/zstart -n -ds -preserve $project >/dev/null"))
{
    die "Failed to start zebra.\n";
}
sleep 5;

@files = `./dfsince LastSounding 2> /dev/null | egrep 'iss.*class'`;
@ftp = ();

foreach $line (@files)
{
    next unless $line =~ /class/;
    ($platform, $file, $dir, $time, $nsample) = split(/\s+/,$line);
    $full = "$dir/$file";

    # Generate JOSS name from file name
    ($year, $mo, $day, $hour, $min, $sec) = 
	$file =~ /\.(\d\d)(\d\d)(\d\d)\.(\d\d)(\d\d)(\d\d)\./;
    $site = $platform;
    $site =~ s,/class,,;
    $ascii = sprintf ("%02d%02d%02d%02d%02d.%s_class.txt",
		      $year, $mo, $day, $hour, $min, $site);
    $site =~ s/iss/is/;
    $ascii = "$joss/$ascii";
    $cmd = "./class2ascii $full LAKE_ICE $site > $ascii";
    print $cmd, "\n";
    system($cmd);
    push (@ftp, $ascii);
}

$cmd = "./ftpjoss.pl " . join(" ",@ftp);
if ($#ftp >= 0)
{
    print $cmd, "\n";
    system ($cmd);
}

exit 0;
