#! /bin/sh
#

html_search_dirs="$HOME/iss/eol /iss/eol /h/eol/iss/iss/eol"

sumplot_beginpage() # heading
{
    cat <<EOF
<html><head><title>$1</title></head><body>
<body bgcolor="#ffffff">
EOF
    # Try to find the standard eol header and insert it.
    hfile=''
    for d in $html_search_dirs ; do
	[ -f "$d/header.html" ] && hfile="$d/header.html" && break
    done
    if [ -n "$hfile" ]; then
	cat "$hfile"
    fi
    # Start the table
cat <<EOF
<table border='0'><tr><td>
<A HREF="http://www.eol.ucar.edu/"><IMG valign=center alt="EOL..." 
   SRC="/graphics/eol_logo_sm.jpg"></a>
</td>
<td>
<IMG alt="National Center for Atmospheric Research" 
     SRC="/gif/ncar_ban_sml.gif">
<br>
<h1>$1</h1>
</td></tr></table>
EOF
}

sumplot_begintable()
{
echo "<p>Click on the thumbnail image to view the full-size image.</p>"
echo "<table border="0" cellspacing=2 cellpadding=2>"
}

sumplot_endtable()
{
echo "</table>"
echo "</p>"
}

sumplot_fillrows() # destdir brightness [numcolumns]
{
test=test
if [ -f /usr/bin/test ]; then
    test=/usr/bin/test
fi
i=0
destdir="$1"
brightness=""
if [ "$2" -ne 0 ]; then
    brightness="+contrast +contrast +contrast"
fi
ncol=4;
if [ $# -ge 3 ]; then
    ncol="$3"
fi
echo "<tr>"
while read path ; do

    if [ $i -eq $ncol ]; then
	i=0
	echo "</tr><tr>"
    fi
    image=`basename $path`
    imagename=`echo $image | sed -e 's/^research\.//' -e 's/\.png$//'`
    destimage="$destdir/tn_$image"
    $test $destimage -nt $path || \
	(set -x; convert +profile '*' -colors 128 -geometry 140x140 $brightness $path $destimage) 1>&2
    echo '<td align=center bgcolor="#f0f0f0">'
    # Shorten the title for images with the long ISS_MAPR_ prefix
    celltitle=`echo "$imagename" | sed -e 's/^ISS_MAPR_[^.]*/MAPR/'`
    echo "<font size=-1><strong>$celltitle<strong></font><br><a href=$path><img src=$destimage></a>"
    echo "</td>"
    i=`expr $i + 1`

done
echo "</tr>"
}


sumplot_filltable()
{
    sumplot_begintable
    sumplot_fillrows "$1" "$2"
    sumplot_endtable
}


sumplot_endpage()
{
    # Try to find the standard eol footer and insert it.
    ffile=''
    for d in $html_search_dirs ; do
	[ -f "$d/footer.html" ] && hfile="$d/footer.html" && break
    done
    if [ -n "$ffile" ]; then
	cat "$ffile"
    else
cat <<EOF
<HR SIZE=6 NOSHADE ALIGN=LEFT>
<FONT SIZE=1>&copy;
NCAR/Atmospheric Technology Division<br>
<a href="http://www.atd.ucar.edu/~granger">Gary Granger</a>
<br><HR WIDTH="100%"><BR>
<P><FONT SIZE=-2>
Created `date`
</FONT></p>
EOF
    fi
echo "</body></html>"
}
