#! /bin/sh
#
# $Id: logimages,v 1.2 1998-01-22 17:52:16 granger Exp $
#
# Simple script to extract the image file names from a batch-plot log

images=`egrep -h '^Images:' $* | sed -e 's/Images://g'`

echo $images

