#! /usr/bin/env perl
#
# $Id: plotindex,v 1.8 2006-04-27 05:48:16 granger Exp $
#
# Create an index.html file from a directory of plot images, so that
# we can control the format and ensure the full file name appears
# in the browser.
#

use strict;

if ($#ARGV < 1)
{
    print "Usage: $0 [options] <project> <date directory> [<date> ...]\n";
    print " -match <regexp>    Only index files matching regexp.\n";
    print "If no <date>, creates index.html in each of the date directories\n";
    print "in <date directory>.  Otherwise creates only <date>/index.html\n";
    exit 1;
}

my $match = ".*";
if ($ARGV[0] eq "-match")
{
    shift @ARGV;
    $match = shift @ARGV;
    print "Matching $match\n";
}
my $project = shift @ARGV;
my $datedir = shift @ARGV;
my @selected = @ARGV;

print "Selected:", join(' ',@selected), "\n";

# Traverse the dates in the directory, creating an index.html for each
# We actually create the index.html for the directory in the previous
# loop iteration, once we know what the "nextdate" directory should be.
my $prevdate = "";
my $date = "";
my $nextdate = "";
my $f;
foreach $f (split(/\s+/,`/bin/ls $datedir`), "")
{
    # print "At $f...\n";
    next if ($f && (($f !~ /^\d+/) || ! -d "$datedir/$f"));
    $nextdate = $f;
    if ($date)
    {
	# print "Checking $date, prev=$prevdate, next=$nextdate\n";
	if ($#selected >= 0)
	{
	    my $d;
	    foreach $d (@selected)
	    {
		# Also need to regenerate dates on either side of selected
		# dates, since the previous and next links on those dates
		# need to change if the target date is new.
		if ($d eq $date || $d eq $prevdate || $d eq $nextdate)
		{
		    &create_index;
		    last;
		}
	    }
	}
	else
	{
	    # If the index.html is already the newest file, and this 
	    # directory was not explicitly selected, no need to
	    # regenerate it.
	    #
	    # Neither of these approaches really works.
	    # if (`ls -t "$datedir/$date" | head -1` =~ /index\.html/)
	    # my $latest=`find "$datedir/$date" -newer "$datedir/$date/index.html" | head -1`;
	    # if ("$latest" !~ /index\.html/)
	    if (0)
	    {
		print "$date already up to date.\n";
	    }
	    else
	    {
		&create_index;
	    }
	}	
    }
    $prevdate = $date;
    $date = $f;
}


sub create_index
{
    my $style = "style='border:2px solid; padding:5px'";
    my $directory = "$datedir/$date";
    print "Indexing $directory, prev=$prevdate, next=$nextdate, ...\n";
    # chdir("$datedir/$date");
    my $title="Project $project plot images for $date";
    open (HTML, "| cd \"$datedir/$date\" && sumplot \"$title\" \'$match\' . . index.html") || 
	die "sumplot: $!";

    print HTML "<table>";
    print HTML "<tr>";
if ($prevdate)
{
    print HTML "<td $style><a href=\"../$prevdate/index.html\">Previous day:</a> <a href=\"../$prevdate/index.html\">$prevdate</a></td>\n";
}
print HTML "<td $style><a href=..>Parent directory</a></td>\n";
if ($nextdate)
{
    print HTML "<td $style><a href=\"../$nextdate/index.html\">Next day:</a> <a href=\"../$nextdate/index.html\">$nextdate</a></td>\n";
}
    print HTML "</tr></table>";
close HTML;

}

# end sub create_index

