#! /bin/sh
#
# $Id: sumplot,v 1.17 2004-03-03 07:36:22 granger Exp $
#
# Collect all the images of a given pattern, reduce their size, and
# put them into a table in the current directory.
#
# Also generate a "quick look" html section of the 2 most recent plots of
# each summary.  The sections can be concatenated to form a status overview
# of several summaries.

brightness=20
if [ "$1" = "-bright" ]; then
    brightness=$2
    shift; shift
fi

if [ $# -ne 5 ]; then

    echo "Usage: $0 [-bright N] <title> <pattern> <basedir> <destdir> <htmlfile>"
    echo "Finds all image files of the given <pattern> under <basedir>"
    echo "and any of its subdirectories, then"
    echo "creates thumbnails in <destdir> and a html table <htmlfile>."
    echo "Any text on standard input is inserted onto the page under the"
    echo "title.  If bright argument N is non-zero, then contrast will be"
    echo "increased in the generated image; used when reducing plot images"
    echo "with dark backgrounds.  Brightening is enabled by default."
    exit 1

fi

title=$1
pattern="$2"
basedir=$3
destdir=$4
htmlfile=$5

if [ ! -d $destdir ]; then
    echo "$destdir does not exist."
    exit 1
fi

findimages()
{
    find $basedir/. -type f -name "${pattern}" | sort
}

. libsumplot
(sumplot_beginpage "$title"

# Insert any text from standard input here
cat

echo "<hr>"

findimages | sumplot_filltable "$destdir" "$brightness"

sumplot_endpage) > $htmlfile.$$
rm -f $htmlfile
mv -f $htmlfile.$$ $htmlfile
echo "Done generating $htmlfile"

# ----------------------------------------------------------------
# Generate a quick summary table section of the four most recent images.
#
number=4
quickpartfile="$htmlfile.quick.part"
findimages | tail -$number | \
(echo "<tr>"
echo "<td align=center colspan=$number><p><strong><a href="$htmlfile">$title</a></strong></p></td></tr>";
sumplot_fillrows "$destdir" "$brightness" $number) > $quickpartfile.$$

rm -f $quickpartfile
mv -f $quickpartfile.$$ $quickpartfile
echo "Done generating $quickpartfile"

