#! /bin/sh

if [ $# -lt 2 ]; then
    echo "Usage: $0 <project-directory> <period>"
    echo "Example:"
    echo "Generate plots for any forestabl data within the last 12 hours:"
    echo "   $0 /net/sssf2/forestabl/forestabl 12"
    exit 1
fi

project=$1
period=$2
shift
shift

exec /net/sssf2/cases99/cases99-iss/zconfig $project zplotd -time `TZ=GMT+$period date +'%e-%h-%Y,%H:00:00'` `date -u +'%e-%h-%Y,%H:00:00'` $*

