#! /bin/sh

if [ "$1" = "-h" ]; then
    echo "Usage: $0 [h1 h2 ...] [-- <zplotd options>]"
    echo "Generate plots for any data since and before the current"
    echo "plot hour.  If no arguments, uses the value of"
    echo "PLOT_HOURS from the project configuration."
    echo "The plot hours need to be in increasing order."
    exit 0
fi

# Separate zplotd options from our plot hours
zplotdargs=""
opthours=""
justecho=0
echo=""
while [ $# -ne 0 ]; do
    case $1 in
    -x) justecho=1 ; echo=echo
	;;
    --) shift; zplotdargs="$zplotdargs $*"
        break
	;;
    *)  opthours="$opthours $1"
	;;
    esac
    shift
done
set skip $opthours
shift

if [ $# -eq 0 ]; then
    set skip $PLOT_HOURS
    shift
else
    PLOT_HOURS="$*"
fi

if [ $# -eq 0 ]; then
    echo "No plot hours.  Exiting."
    exit 1
fi

echo "Plot hours: $*"

currenthour=`date -u '+%H'`
h1=99
h2=99
hlast=0
hfirst=$1
doplot2=0
for h in $*; do

    if [ $h -lt $currenthour ]; then
	h1=$h
	doplot2=1
    elif [ $h -eq $currenthour ]; then
	h1=$h
	doplot2=0
    elif [ $h2 -eq 99 ]; then
	h2=$h
    fi
    hlast=$h

done

# If h1 is set, then the first plot time is on the current day at
# the plot hour given by h1.
# If h1 is not set, then the first plot time is the
# last plot hour on the previous day, which we find by shifting timezone.
# Also, unset h1 means the current hour does not equal the plot hour,
# so we're more than one hour into the second plot period and should plot it.
if [ $h1 -ne 99 ]; then
    plot1=`date -u +"%d-%h-%Y,$h1:00:00"`
else
    doplot2=1
    plot1=`TZ=GMT+24 date +"%d-%h-%Y,$hlast:00:00"`
fi

# Similar setup for the second plot time, except we have to advance a day
# if no plot hours found greater than the current hour.
if [ $h2 -ne 99 ]; then
    plot2=`date -u +"%d-%h-%Y,$h2:00:00"`
else
    plot2=`TZ=GMT-24 date +"%d-%h-%Y,$hfirst:00:00"`
fi

# Any reason this can't be run in parallel?  Leaving serial for now...
# Run the second plot if the current hour is not also the plot hour.
set -x
$echo zplotd -period $plot1 $zplotdargs
if [ $doplot2 -ne 0 ]; then
    $echo zplotd -period $plot2 $zplotdargs
fi

