#! /bin/sh

if [ $# -lt 1 ]; then
    echo "Usage: $0 <period>"
    echo "Example:"
    echo "Generate plots for any forestabl data within the last 12 hours:"
    echo "   $0 12"
    echo "where the minutes and seconds are automatically reset to zero."
    echo "This script expects to be run with the proj_env settings, such"
    echo "as through zconfig."
    exit 1
fi

period=$1
shift

exec zplotd -time `TZ=GMT+$period date +'%d-%h-%Y,%H:00:00'` `date -u +'%d-%h-%Y,%H:00:00'` $*

