#! /usr/bin/env perl
#
# $Id: ztsplit,v 1.8 2002-06-10 22:03:04 granger Exp $
#
# Split zebra times into yy mm dd hour min sec
#

if ($#ARGV != 0)
{
    print "Usage: ztsplit <time>\n";
    exit 1;
}

if ( ! $ENV{'ZEB_TOPDIR'} ) { die "ZEB_TOPDIR must be set."; }
push(@INC,"$ENV{'ZEB_TOPDIR'}/bin");
require libzplot;

($year, $month, $day, $hour, $min, $sec) = ztsplit ($ARGV[0]);
printf "%d %02d %02d %02d %02d %02d\n",
    $year, $month, $day, $hour, $min, $sec;

exit 0;
