       PARAMETER (MAXDIM=25, MAXSTN=200, LUIN=5, LUOUT=6)
C MAXDIM = LARGEST DIMENSION ALLOWED FOR THE GRID USED FOR MESONET DATA.
C MAXSTN = MAXIMUM NO. OF PAM STATIONS.
C LUIN = LOGICAL UNIT NO. FOR INPUT.
C LUOUT = LOGICAL UNIT NO. FOR OUTPUT.
	CHARACTER*10	NAME
	CHARACTER*7	FSTRNG,OVFLD
	LOGICAL		DELETED
	COMMON /TRIAGD/	NP, ITRS, IUSED(MAXSTN), ITRNGL(MAXSTN,6),
     *			NAPROX, IBPTNO, IBPTS, IBNDRY(MAXSTN), NSTNS,
     *			NX, NY, IPAR, IALT(MAXSTN), NFLTR, 
     *			DELETED(MAXSTN), NUSRNO(MAXSTN), IDATE, ITIME,
     *			NTPLOT, NSTEP, IPAROV, JW(MAXDIM,MAXDIM),
     *			X(MAXSTN), Y(MAXSTN), FLAG, XMAX, XMIN, YMAX,
     *			YMIN, X0, Y0, DX, DY, OVRPAM(MAXSTN), 
     *			AREA(MAXSTN), U(MAXSTN), V(MAXSTN), Z(MAXSTN),
     *			RLAT(MAXSTN), RLON(MAXSTN), WEIGHT(MAXSTN,6),
     *			RUPLIM(200), RLOLIM(200)
	COMMON /TRGCHR/	FSTRNG, OVFLD, NAME
