      FUNCTION CFD(XVALU,IDEC)
C *** McIDAS Revision History ***
C 1 CFD.FOR 3-Apr-90,13:16:28,`SSEC' PC-McIDAS ver 5.00
C 2 CFD.FOR 24-Sep-90,18:20:36,`SMG' First Release into COMmon
C *** McIDAS Revision History ***
C $ CFD(XVALUE, IDEC)  (RCD)
C $ CONVERT REAL*8 TO CHARACTER*12 WITH LEADING BLANKS RATHER THAN ZEROS
C $ XVALU = (R*8) INPUT  REAL*8 TO CONVERT
C $ IDEC = (I) INPUT  NUMBER OF DESIRED DECIMAL PLACES
C $$ CFD = CONVERT, REAL, CHARACTER
C-----DECIMAL PART ALWAYS HAS (SIGN IF NEG) + DECIMAL POINT +
C-----'IDEC' (0 TO LENGTH-6) FRACTIONAL DIGITS. 4 PLACES ARE RESERVED
C-----IN THE OUTPUT FIELD FOR THE EXPONENT (THEY MAY NOT ALL BE USED);
C-----OUTPUT LOOKS LIKE, E.G., .172E3; .95E-16; -.10006E-4
C
      PARAMETER (LENGTH=12)
      IMPLICIT REAL*8 (X-Z)
      CHARACTER*12 CFD
C-----MAX DEC DIGIT PRECISION FOR 32-BIT WORD (REF. DPSINO)
      PARAMETER ( MXPREC=09)
      PARAMETER (IZERO=48)
C
C
C
      JDEC=MIN0(MAX0(IDEC,1),MXPREC,LENGTH-6)
      JLEFT= LENGTH-JDEC-3
      CFD(1:JLEFT)='                '
C
C-----CONVERT TO SCALED-INTEGER FORM
C
      CALL DPSINO(JDEC,XVALU,ISCALE,IVAL,IERR)
      IF (IERR.NE.0) GOTO 91
C
C-----CONVERT NORMALIZED VALUE TO EBCDIC
C
 10   IF (IVAL.LT.0) THEN
         CFD(JLEFT-2:JLEFT-2)='-'
      ELSE
         CFD(JLEFT-2:JLEFT-2)='+'
      ENDIF
      CFD(JLEFT-1:JLEFT-1)='.'
      JVAL=IABS(IVAL)
      DO 20 J=JLEFT+JDEC-1,JLEFT,-1
         CFD(J:J)=CHAR(MOD(JVAL,10)+IZERO)
         JVAL=JVAL/10
 20   CONTINUE
C
C-----PUT OUT EXPONENT
C
      K=JLEFT+JDEC
      IEXPON=0
      IF (IVAL.NE.0) IEXPON=JDEC-ISCALE
      IF (IEXPON.GE.0) CFD(K:K+1)='E+'
      IF (IEXPON.LT.0) CFD(K:K+1)='E-'
      L=MIN0(99,IABS(IEXPON))
      CFD(K+2:K+3)=CHAR(L/10+IZERO)//CHAR(MOD(L,10)+IZERO)
      RETURN
C
C-----ERROR
C
 91   CFD(1:LENGTH)='****************'
 99   RETURN
      END
