      FUNCTION FLALO(M)
C *** McIDAS Revision History ***
C 1 FLALO.FOR 19-Mar-90,21:49:24,`SSEC' PC-McIDAS ver 5.00
C 2 FLALO.FOR 25-Sep-90,7:33:56,`SMG' First Release into COMmon
C *** McIDAS Revision History ***
C $ FUNCTION FLALO(M)  (BL)
C $ CONVERT PACKED INTEGER (SIGN DDD MM SS) LATITUDE-LONGITUDE TO REAL*4
C $ M = (I) INPUT  PACKED INTEGER (SIGN DDD MM SS) LATITUDE-LONGITUDE
C $$ FLALO = CONVERT, INTEGER, LATITUDE, LONGITUDE, REAL
C
      IF(M.LT.0)GO TO 1
      N=M
      X=1.0
      GO TO 2
 1    N=-M
      X=-1.0
 2    FLALO=FLOAT(N/10000)+FLOAT(MOD(N/100,100))/60.0+FLOAT(MOD(N,100))/
     13600.0
      FLALO=X*FLALO
      RETURN
      END
