C   THIS IS SSEC PROPRIETARY SOFTWARE - ITS USE IS RESTRICTED.

C *** McIDAS Revision History ***
C 1 HEX80.INC 2-Oct-90,9:45:10,`SMG' initial release to AIX
C 2 HEX80.INC 16-Feb-92,14:32:54,`USER' Released for McIDAS-X Only
C 3 HEX80.INC 1-Apr-94,0:48:12,`BARRYR' Add proprietary statement
C 4 HEX80.INC 2-May-94,16:00:30,`USER' Released for McIDAS-X Only
C 5 HEX80.INC 19-Feb-96,15:03:22,`DWS' reglue: moved from AIX to COM
C 6 HEX80.INC 20-Feb-96,12:41:56,`USER' Released for McIDAS-X Only
C *** McIDAS Revision History ***

      INTEGER    HEX80
      PARAMETER (HEX80=Z'80808080')
