C   THIS IS SSEC PROPRIETARY SOFTWARE - ITS USE IS RESTRICTED.
      FUNCTION IROUND(X)
C *** McIDAS Revision History ***
C 1 IROUND.FOR 16-Mar-90,16:38:50,`SSEC' PC-McIDAS ver 5.00
C 2 IROUND.FOR 25-Sep-90,7:34:30,`SMG' First Release into COMmon
C 3 IROUND.FOR 1-Apr-94,1:17:16,`BARRYR' Add proprietary statement
C 4 IROUND.FOR 2-May-94,16:48:14,`USER' Released
C *** McIDAS Revision History ***
C $ FUNCTION IROUND(X)  (JMB)
C $ ROUNDS A FLOATING POINT VALUE
C $ X = (R) INPUT  FLOATING POINT VALUE
C $$ IROUND = REAL
C
      IROUND=NINT(X)
      RETURN
      END
