C   THIS IS SSEC PROPRIETARY SOFTWARE - ITS USE IS RESTRICTED.

C *** McIDAS Revision History ***
C 1 LBCHEK.FOR 6-Mar-90,13:37:38,`SSEC' PC-McIDAS ver 5.00
C 2 LBCHEK.FOR 25-Sep-90,7:36:18,`SMG' First Release into COMmon
C 3 LBCHEK.FOR 1-Apr-94,1:20:32,`BARRYR' Add proprietary statement
C 4 LBCHEK.FOR 2-May-94,16:54:44,`USER' Released
C 5 LBCHEK.FOR 19-Feb-96,15:55:14,`DWS' reglue: modified file
C 6 LBCHEK.FOR 20-Feb-96,11:55:38,`USER' Released
C *** McIDAS Revision History ***

C $ SUBROUTINE LBCHEK  (RCD)
C $ READ STRING TABLE FOR TERMINAL 'LBTERM' INTO COMMON IF NOT ALREADY
C $   THERE.
C $ LBCHEK = STRING-TABLE

      SUBROUTINE LBCHEK
      IMPLICIT CHARACTER*12 (C)
	EQUIVALENCE (CTBL,ICTBL)
      CHARACTER*160 CSTR
      COMMON/LBCOM1/LBTERM,LBBEG,LBN,LENTBL(256)
      COMMON/LBCOM2/CSTR,CLBH,CLBY,CTBL(256)
      PARAMETER (NTOT=15*1024)
      DATA CFILE/'STRTABLE'/
C
C
C---------concept of 'terminal' is obsolete
      LBTERM=0

         LBBEG=LBTERM*NTOT
         LWRETN=LWI(CFILE,LBBEG,256,LENTBL)
         CALL SWBYT4(LENTBL,256)            ! <<<<< UPC mod 961029 >>>>>
         LWRETN=LWI(CFILE,LBBEG+256,256*3,ICTBL)
         DO 2 J=256,3,-1
            IF (LENTBL(J).GT.0) GOTO 4
 2       CONTINUE
         J=2
 4       LBN=J
C-----   SET UP #H
         CTBL(1)='H'
         LENTBL(1)=10
         CALL GETTIM(ITIME)
         CTEMP=CFI(ITIME+1000000)
         IF (CTEMP(7:7).EQ.'0') CTEMP(7:7)=' '
C-----   SET UP #Y
         CTBL(2)='Y'
         LENTBL(2)=5
         CLBH=CTEMP(7:8)//':'//CTEMP(9:10)//':'//CTEMP(11:12)
         CALL GETDAY(IDAY)
         CTEMP=CFI(IDAY)
         CLBY=CTEMP(8:12)
 90   RETURN
      END
