C   THIS IS SSEC PROPRIETARY SOFTWARE - ITS USE IS RESTRICTED.

C *** McIDAS Revision History ***
C 1 M0ITIME.FOR 19-Feb-96,15:17:24,`DWS' reglue: new file
C 2 M0ITIME.FOR 20-Feb-96,12:11:02,`USER' Released
C *** McIDAS Revision History ***

C $ FUNCTION M0ITIME(X)  (JMB)
C $ FLOATING POINT TIME TO PACKED INTEGER ( SIGN HH MM SS )
C $ X = (R) INPUT  FLOATING POINT TIME

      INTEGER FUNCTION M0ITIME(X)
      IMPLICIT NONE
      REAL X

C --- local variables

      INTEGER I
      INTEGER J
      REAL Y

      IF(X.LT.0.0)GO TO 1
      Y=X
      I=1
      GO TO 2
 1    Y=-X
      I=-1
 2    J=3600.0*Y+0.5
      M0ITIME=10000*(J/3600)+100*MOD(J/60,60)+MOD(J,60)
      M0ITIME=I*M0ITIME
      RETURN
      END
