C   THIS IS SSEC PROPRIETARY SOFTWARE - ITS USE IS RESTRICTED.
      FUNCTION NTHDAY(NY,NM,ND)
C *** McIDAS Revision History ***
C 1 NTHDAY.FOR 17-Apr-90,8:01:42,`SSEC' PC-McIDAS ver 5.00
C 2 NTHDAY.FOR 24-Sep-90,18:19:48,`SMG' First Release into COMmon
C 3 NTHDAY.FOR 1-Apr-94,1:32:00,`BARRYR' Add proprietary statement
C 4 NTHDAY.FOR 2-May-94,17:13:52,`USER' Released
C *** McIDAS Revision History ***
CNP   NTHDAY
C $ FUNCTION NTHDAY(NY,NM,ND)
C $ GET THE NTH DAY OF THE YEAR, GIVEN CALENDAR DATE
C $ NY = (I) INPUT  YEAR
C $ NM = (I) INPUT  MONTH
C $ NM = (I) INPUT  DAY
C $$ NTHDAY = CONVERT,DATE,VAS
C
      KODE = 1115212
      IF(MOD(NY,4) .EQ. 0) KODE = 1115208
      NTH = ND
      IF(NM .LE. 1) GO TO 120
      NTH = 0
      M = NM - 1
C
      DO 110 J = 1,M
      NTH = NTH + 31 - MOD(KODE,4)
110   KODE = KODE/4
C
      NTH = NTH + ND
C
120   NTHDAY = NTH
      RETURN
      END
