      SUBROUTINE SOLARP(JDAY,JTIME,GHA,DEC,XLAT,XLON)
C *** McIDAS Revision History ***
C 1 SOLARP.FOR 23-Mar-90,12:34:48,`SSEC' PC-McIDAS ver 5.00
C 2 SOLARP.FOR 25-Sep-90,7:36:38,`SMG' First Release into COMmon
C *** McIDAS Revision History ***
C SOLARP MOSHER 1074 WINLIB  Z HOUR ANGLE AND SOLAR DECL FOR DAY-TIME
C $ SUBROUTINE SOLARP(JDAY, JTIME, GHA, DEC, XLAT, XLON)  (DAS)
C $ COMPUTES GREENWICH HOUR ANGLE AND DECLINATION OF SUN
C $ JDAY = (I) INPUT  SATELLITE/YEAR/DAY
C $ JTIME = (I) INPUT  HOUR/MINUTE/SECOND
C $ GHA = (R) OUTPUT  GREENWICH HOUR ANGLE
C $ DEC = (R) OUTPUT  DECLINATION
C $ XLAT = (R) OUTPUT  LATITUDE OF SUN POSITION
C $ XLON = (R) OUTPUT  LONGITUDE OF SUN POSITION
C $$ SOLARP = COMPUTATION, NAVIGATION
C
C     ORBITAL CONSTANTS
C
C     IEPYD = EPOCH YEAR-DAY
C     IEPHMS = EPOCH HOUR-MINUTE-SECOND
C     OECCEN = ECCENTRICITY OF EARTH ORBIT
C     OINCLI = INCLINATION TO CELESTIAL EQUATOR
C     PERHEL = PERIHELION
C     ASNODE = ASCENDING NODE
C     XMANOM = MEAN ANOMOLY
C     XMMC = MEAN MOTION CONSTANT
C     SHA = CELESTIAL HOUR ANGLE
C     IRAYD  =  YYDDD WHEN CELESTIAL COOR. SYS. COINCIDES WITH EARTH COO
C     IRAHMS = HHMMSS WHEN CELESTIAL COOR. SYS. COINCIDES WITH EARTH COO
C
      REAL*8 DIFTIM,ECANM1,ECANOM,RAHA,TIMDIF,XHA,XMANOM
C     REAL*8 DABS,DMOD,DSQRT,DSIN,DCOS,DATAN2
      DATA INIT/0/
C
C
      IF(INIT.NE.0)GO TO 1
      INIT=1
      PI=3.14159265
      RDPDG=PI/180.0
      SOLSID=1.00273791
      IEPYD=74004
      IEPHMS=0
      OECCEN=0.016722
      OINCLI=RDPDG*FLALO(232700)
      PERHEL=RDPDG*FLALO(1011311)+PI
      ASNODE=RDPDG*FLALO(0)
      XMMC=.01720209895/1440.0
      SHA=100.26467
      IRAYD=74001
      IRAHMS=0
      SINC=SIN(OINCLI)
      CINC=COS(OINCLI)
      SPER=SIN(PERHEL)
      CPER=COS(PERHEL)
      SAND=SIN(ASNODE)
      CAND=COS(ASNODE)
      PX=CPER*CAND-SPER*SAND*CINC
      PY=CPER*SAND+SPER*CAND*CINC
      PZ=SPER*SINC
      QX=-SPER*CAND-CPER*SAND*CINC
      QY=-SPER*SAND+CPER*CAND*CINC
      QZ=CPER*SINC
 1    IDAY=MOD(JDAY,100000)
      PTIME=FTIME(JTIME)
      DIFTIM=TIMDIF(IEPYD,IEPHMS,IDAY,JTIME)
      XMANOM=XMMC*DIFTIM
      ECANM1=XMANOM
      EPSILN=1.0E-8
      DO 2 I=1,20
      ECANOM=XMANOM+OECCEN*SIN(ECANM1)
      IF(ABS(ECANOM-ECANM1).LT.EPSILN)GO TO 3
 2    ECANM1=ECANOM
 3    XOMEGA=DCOS(ECANOM)-OECCEN
      YOMEGA=SQRT(1.0-OECCEN**2)*DSIN(ECANOM)
      XFACT=1.0/SQRT(XOMEGA**2+YOMEGA**2)
      XOMEGA=XOMEGA*XFACT
      YOMEGA=YOMEGA*XFACT
      XS=XOMEGA*PX+YOMEGA*QX
      YS=XOMEGA*PY+YOMEGA*QY
      ZS=XOMEGA*PZ+YOMEGA*QZ
      SLRA=ATAN2(YS,XS)/RDPDG
      RAHA=TIMDIF(IRAYD,IRAHMS,IDAY,JTIME)*SOLSID/4.0
      GHA=PTIME*15.0
      XHA=360.0-SHA-RAHA+SLRA+GHA
      GHA=DMOD(XHA,360.0D0)
      GHA=360.0-GHA-2.0
      DEC=ATAN2(ZS,SQRT(XS**2+YS**2))/RDPDG
      XLAT=GEOLAT(DEC*RDPDG,1)/RDPDG
      XLON=-GHA-PTIME*15.0+720.0
      XLON=AMOD(XLON,360.0)
      RETURN
      END
