      FUNCTION VOLNAM(CIN,COUT)
C *** McIDAS-AIX Revision History ***
C 1 VOLNAM.FOR 21-Dec-90,9:37:16,`SMG' first release to AIX
C 2 VOLNAM.FOR 7-Nov-91,15:28:34,`SUEG' change cin, cout def to char *(*)
C 3 VOLNAM.FOR 16-Feb-92,14:49:36,`USER' Released for McIDAS-X Only
C 4 VOLNAM.FOR 10-Feb-93,11:54:48,`SUEG' implement redirect 3587
C 5 VOLNAM.FOR 25-Feb-93,14:30:18,`SUEG' longer path for redirect 3587
C 6 VOLNAM.FOR 12-Mar-93,10:00:54,`USER' Released for McIDAS-X Only
C 7 VOLNAM.FOR 3-Sep-93,12:22:28,`RUSSD' Take out unused variables (4069)
C 8 VOLNAM.FOR 4-Oct-93,13:50:46,`USER' Released for McIDAS-X Only
C *** McIDAS-AIX Revision History ***
C     VOLNAM: RETURNS THE DOS PATH OF A McIDAS DATA FILE
C           CIN (C) - INPUT  FILE NAME TO CHECK FOR ALTERNATE PATH
C           COUT (C) - OUTPUT  FILE WITH APPENDED PATH
C           FUNC VAL - 0=DEFAULT PATH, >0=PATH FOUND

      IMPLICIT INTEGER(A-B,D-Z)
      IMPLICIT CHARACTER*12 (C)

      CHARACTER*(*) CIN,COUT
      CHARACTER*72 CPATH
      CHARACTER*4 CEXT

      COMMON/LWADD/ LWADDR
      COMMON/LWPATH/ FLEN,ELEN,PLEN,CFILE,CEXT,CPATH

      PARAMETER (NBYTE=100)
      PARAMETER (MAXLEN=72)

C--- INITAILIZE THE FUNCTION VALUE
      VOLNAM=0

C--- CHECK FOR A VALID FILE NAME
      NUM=LEN_TRIM(CIN)
      IF(NUM.LE.0) THEN
            COUT = ' '
            RETURN
      ENDIF

C--- CHECK THE FILE NAME FOR EXTENSION
      PERIOD=INDEX(CIN,'.')
      IF(PERIOD.NE.0) THEN
            CINEXT=CIN(PERIOD:NUM)
            CINFIL=CIN(1:PERIOD-1)
      ELSE
            CINEXT=' '
            CINFIL=CIN
      ENDIF

C--- READ THE NUMBER OF PATHS ( WORD(0) )
      CALL MOVBMEM(4,LWADDR,LADDR(NPATH),0)
      IF(NPATH.LE.0) GOTO 200



C--- LOOP THROUGH THE PATH FILE
      DO 100 I=1,NPATH
      OFFSET=(I-1)*NBYTE+4
      NEWADD=LWADDR+OFFSET
      INADD=LADDR(FLEN)
      CALL MOVBMEM(NBYTE,NEWADD,INADD,0)
C--- SCAN THE NAMES FOR A MATCH
      DO 20 J=1,FLEN
      IF(CFILE(J:J).EQ.'*') GOTO 21
      IF(CFILE(J:J).EQ.'?') GOTO 20
      IF(CFILE(J:J).NE.CINFIL(J:J)) GOTO 100
20    CONTINUE

C--- NAMES MATCH, CHECK EXTENSIONS
21    IF(PERIOD.NE.0) THEN
            IF(ELEN.EQ.0) GOTO 100
            DO 30 J=1,ELEN
            IF(CEXT(J:J).EQ.'*') GOTO 31
            IF(CEXT(J:J).EQ.'?') GOTO 30
            IF(CEXT(J:J).NE.CINEXT(J:J)) GOTO 100
30          CONTINUE
      ELSE
            IF(ELEN.NE.0) GOTO 100
      ENDIF

C--- MAKE SURE NAME IS .LE. MAXLEN
31    TOTAL=PLEN+NUM
      IF(CPATH(PLEN:PLEN).NE.'/') TOTAL=TOTAL+1
      IF(TOTAL.GT.MAXLEN) THEN
        CALL EDEST('Path name is too long -- Redirection failed',0)
        GOTO 200
      ENDIF

C--- ADD THE PATH TO THE FILE NAME
      IF(CPATH(PLEN:PLEN).EQ.'/') THEN
        COUT=CPATH(1:PLEN)//CIN(1:NUM)
      ELSE
        COUT=CPATH(1:PLEN)//'/'//CIN(1:NUM)
      ENDIF
      VOLNAM=I
      RETURN

100   CONTINUE

C--- NO MATCH FOUND --> DEFAULT PATH
200   COUT=CIN(1:NUM)
      VOLNAM=0

      RETURN
      END

