/*
 * $Id: version.h,v 1.13 1996-09-19 14:48:36 granger Exp $
 *
 * Include various symbols, compilation, and version info into an object
 * file.  We try to take advantage of ANSI C pre-preprocessors as much as
 * possible, as well as allowing for the use what(1) or ident(1) to identify
 * version information.
 */

#ifndef _zebra_version_h__
#define _zebra_version_h__

#include "config.h"

#if !defined(SABER) && !defined(lint) && !defined(LINT)

#if __STDC__

static const char cppsyms[] = "@(#)$Symbols: "
" __STDC__ "
#ifdef _POSIX_SOURCE
" _POSIX_SOURCE "
#endif
#ifdef __GNUC__
" __GNUC__ "
#endif
#ifdef __STRICT_ANSI__
" __STRICT_ANSI__ "
#endif
#ifdef X_NOT_STDC_ENV
" X_NOT_STDC_ENV "
#endif
#ifdef X_NOT_POSIX
" X_NOT_POSIX "
#endif
#ifdef SYSV
" SYSV "
#endif
#ifdef SVR4
" SVR4 "
#endif
#ifdef BSD
" BSD "
#endif
#ifdef SHM
" SHM "
#endif
#ifdef CFG_NC_DCATTS_OVERRIDE
" CFG_NC_DCATTS_OVERRIDE "
#endif
#ifdef CFG_NO_BADVALUES
" CFG_NO_BADVALUES "
#endif
#ifdef CFG_NC_NO_ALT_UNITS
" CFG_NC_NO_ALT_UNITS "
#endif
#ifdef ARM_PROJECT
" ARM_PROJECT "
#endif
#ifdef NEXUS_PROJECT
" NEXUS_PROJECT "
#endif
#ifdef BASEDIR
"BASEDIR:" BASEDIR " "
#endif
#ifdef BINDIR
"BINDIR:" BINDIR " "
#endif
#ifdef LIBDIR
"LIBDIR:" LIBDIR " "
#endif
#ifdef AutoBuild
" AutoBuild "
#endif
" $";
#else /* ! __STDC__ */
# ifndef __STDC__
static char cppsyms[] = "@(#)$Symbols: __STDC__ not defined $";
# else
static char cppsyms[] = "@(#)$Symbols: __STDC__ defined as 0 $";
# endif /* ndef __STDC */
#endif /* __STDC__ */

#if __GNUC__
static inline const
#else
static
#endif
char *Z_cppsymbols() { return ((char *)cppsyms); }

#endif /* !SABER && !lint */

/*-----------------------------------------------------------------------
 * Version management macros
 */

/* Note that any necessary semi-colons are already included and should
 * not be added when invoked in code.  Prepending "@(#)" allows version
 * info to be found by both ident(1) (RCS) and what(1) (SCCS).
 * Other RCS info, besides the Id, can be generated by using
 * differently named macros, which define different static char symbols.
 * The compile date and time are only included with RCSID.
 */

#if defined(lint) || defined(LINT) || defined(SABER)

#define RCSID(id) 

#else
#if __GNUC__
#define RCSID(id) \
static inline const char *Z_rcsid() { \
static const char rcs_id[] = "@(#)" id ;			  \
static const char compileid[] = 			  \
	"@(#)" "$Compiled: " __FILE__ " on " __DATE__ " at " __TIME__ " $"; \
static char buf[256]; \
sprintf (buf, "%s\n%s\n", rcs_id, compileid); \
return (buf); \
}

#else /* !__GNUC__ */
#if __STDC__

#define RCSID(id) \
static const char *Z_rcsid() { \
static const char rcs_id[] = "@(#)" id ;			  \
static const char compileid[] = 			  \
	"@(#)" "$Compiled: " __FILE__ " on " __DATE__ " at " __TIME__ " $"; \
static char buf[256]; \
sprintf (buf, "%s\n%s\n", rcs_id, compileid); \
return (buf); \
}

#else /* !__STDC__ */
/*
 * These defs are not as complete as above. And the 'what' flags may be
 * lost on optimization or not left preceding the RCS string.
 */

#define RCSID(id) \
static char *Z_rcsid() { \
static const char i_sccsid[4] = { '@', '(', '#', ')' }; \
static const char rcs_id[] = id ; \
static char buf[256]; \
sprintf (buf, "%s%s\n", i_sccsid, rcs_id); \
return (buf); \
}

#endif /* __STDC__ */
#endif /* __GNUC__ */
#endif /* lint */


#if !defined(lint) && !defined(LINT) && !defined(SABER)

/*
 * Hand edit these lines until it can be done automatically.  One possibility
 * is using the RCS state field, but even that requires running a command
 * manually.  Perhaps an explicit version tag script which tags with CVS as
 * well as updating the ChangeLog and this file.
 */
#define ZV1 "@(#)$ZebraVersion: 4.2.x $"
#define ZV2 "@(#)$ZebraVersion: Research Data Program, NCAR $"
#define ZV3 \
   "@(#)$Copyright: University Corporation for Atmospheric Research, 1996 $"

static const char zebra_version_id1[] = ZV1;
static const char zebra_version_id2[] = ZV2;
static const char zebra_version_id3[] = ZV3;

#if __GNUC__
static inline const char *Z_version ()
#else
static char *Z_version ()
#endif
{
	static char buf[256];

	sprintf (buf, "%s\n%s\n%s\n", zebra_version_id1, zebra_version_id2,
		 zebra_version_id3);
	return (buf);
}

#undef ZV1
#undef ZV2
#undef ZV3

#endif /* lint, LINT, and SABER */

#endif /* !_zebra_version_h__ */
